### ISSUE TITLE
Building instructions unclear...

### ISSUE THREAD

**Issue by joyel24** [cfint/esp32-a2dp-sink#8]
Building instructions are very limited...
It seems to need some specific version, specific branch of esp-idf + some specific codec.
It could be complicated to add this specific development configuration only to build and flash a microcontroller 1 time to use it...

@cfint  Can you provide a dockerfile with every dependencies to be able to build it easily ? Or can you at least give us a firmware .bin in release section to flash an ESP32 module and test if APTX and LDAC are working as expected ?

**Comment by Fogacius** [comment]
# ESP32 A2DP Sink Setup Tutorial

This guide will walk you through the steps to set up and build the **ESP32 A2DP Sink** project using the **ESP-IDF** framework, with dependencies for **APTX** and **LDAC** codecs. It is designed to address specific issues related to the versions and branches of libraries required.

## Prerequisites

Before starting, make sure you have the following installed on your system:
- **Git**
- **Python 3** (preferably in a virtual environment for better dependency management)
- **ESP-IDF** dependencies (you can install them using `install.sh`)

### Step 1: Clone the ESP32 A2DP Sink Repository

Start by cloning the main repository for the **ESP32 A2DP Sink** project:

```bash
git clone --recursive --branch v5.1 https://github.com/cfint/esp32-a2dp-sink.git
```

### Step 2: Clone the ESP-IDF Repository

Next, clone the ESP-IDF repository. Be sure to use the specific branch v5.1.4-a2dp-codecs as required for this project:

```bash
git clone --recursive --branch v5.1.4-a2dp-codecs https://github.com/cfint/esp-idf.git
```

### Step 3: Navigate to the External Bluetooth Directory

Now navigate to the specific directory for Bluetooth components in the ESP-IDF repository:

```bash
cd esp-idf/components/bt/host/bluedroid/external/
```
### Step 4: Clone the libfreeaptx Library

Clone the libfreeaptx repository into this directory:

```bash
git clone --recursive --branch master https://github.com/cfint/libfreeaptx-esp
```

### Step 5: Rename the Directory

You will need to rename the directory from libfreeaptx-esp-main to libfreeaptx:

```bash
mv libfreeaptx-esp-main/ libfreeaptx/
```

### Step 6: Clone the arduino-fdk-aac Repository

Clone the arduino-fdk-aac library which is needed for AAC codec support:

```bash
git clone --recursive --branch idf_component https://github.com/cfint/arduino-fdk-aac
```

### Step 7: Clone the libldac-dec Library

Clone the libldac-dec library for LDAC codec support:

```bash
git clone --recursive --branch esp32 https://github.com/cfint/libldac-dec
```

### Step 8: Return to the Main Folder

Now you need to return to the main directory where you initially cloned the two repositories:

```bash
cd ../../../../../../
```

### Step 9: Navigate to ESP-IDF Directory

Go back to the esp-idf directory:

```bash
cd esp-idf/
```

### Step 10: Install ESP-IDF Dependencies

Run the install.sh script to install all required dependencies:

```bash
sh install.sh
```

Note: If you encounter issues related to system dependencies, try running install.sh within a Python virtual environment (venv).
### Step 11: Source the Environment Variables

Once the installation is complete, source the environment variables to set up the ESP-IDF environment:

```bash
source export.sh
```

### Step 12: Modify Configuration (Optional)

You can modify the esp32-a2dp-sink/main/main.cpp file to suit your configuration needs. Additionally, you can use the menuconfig tool to configure the project like any other ESP-IDF project:

```bash
idf.py menuconfig
```
This command will launch the interactive configuration tool, where you can change various project settings, including WiFi, Bluetooth, codec options, and more.

### Step 13: Build the Project

Navigate to the esp32-a2dp-sink directory and start the build process:

```bash
cd ../esp32-a2dp-sink/
idf.py build
```

### Troubleshooting
- The installation process for ESP-IDF is similar to the official process. If you encounter errors during the installation or build, check the official documentation or search online for solutions.
- When building the project on different operating systems, like Arch Linux or Ubuntu, some dependencies may cause issues. On Arch Linux, I had to run install.sh from inside a Python virtual environment (venv).

**Comment by kmdk1** [comment]
Hi @Fogacius,

Thanks for the guide, really helped with the confusion of setting up the IDF through the commandline. However, I'm wondering if you ran into this issue as well: 

Traceback (most recent call last):
  File "/home/karel/esp/esp-idf/tools/kconfig_new/menuconfig_wrapper.py", line 60, in <module>
    main()
    ~~~~^^
  File "/home/karel/esp/esp-idf/tools/kconfig_new/menuconfig_wrapper.py", line 17, in main
    menuconfig._main()
    ^^^^^^^^^^^^^^^^
AttributeError: module 'menuconfig' has no attribute '_main'

Run into this both under Windows and under Ubuntu, tried running install.sh/.ps1 from within a venv and that didn't help much. Menuconfig no workie and the compilation seems to fail as well. Is this a bug in the 5.1.4-a2dp-codecs IDF branch? Or should I use a specific version of Python or something? (Installed the prereqs according to the espressif documentation for IDF 5.1.6, command was 'sudo apt-get install git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0').

**Comment by lakmithk2-droid** [comment]
Hey so i'm not sure if you found the solution, but i'll leave it here if anyone else comes across the same problem

all you have to do is uninstall kconfig file then reinstall version 1.5 of kconfig

for windows cmd just type ;

    pip uninstall esp-idf-kconfig

and followed by ;
 
    pip install esp-idf-kconfig==1.5.0

**Comment by kmdk1** [comment]
Yep, I found this out after much frustration and forgot to post it here. Works flawlessly now, except the LDAC. But whatever, it's a battery hog anyway.
